### ISSUE TITLE
BUG: Client.fromSharedAccessSignature not working properly

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdks#349]
File: \node_modules\azure-iot-device\lib\client.js Line 141:
Original code:

```
var sas = SharedAccessSignature.parse(sharedAccessSignature);
var uriSegments = sas.sr.split('/')[0];
var config = {
    host: uriSegments[0],
    deviceId: uriSegments[uriSegments.length - 1],
    hubName: uriSegments[0].split('.')[0],
    sharedAccessSignature: sharedAccessSignature
};
```

**Problem 1**: var uriSegments = sas.sr.split('/')[0];
The device uri looks something like this: "myHub-devices.net/devices/device1" which makes uriSegments =  "myHub-devices.net" from which other properties like deviceId can't be parsed.

**Problem 2**:Uri is likely to be encoded and can not be split using sas.sr.split('/')

**Suggestion**:
```
Client.fromSharedAccessSignature = function (sharedAccessSignature, Transport) {
  /*Codes_SRS_NODE_DEVICE_CLIENT_16_029: [The fromSharedAccessSignature method shall throw a ReferenceError if the sharedAccessSignature argument is falsy.] */
  if (!sharedAccessSignature) throw new ReferenceError('sharedAccessSignature is \'' + sharedAccessSignature + '\'');

    var sas = SharedAccessSignature.parse(sharedAccessSignature);
    var uri = decodeURIComponent(sas.sr); 
    var uriSegments = uri.split('/');
    
    var config = {
        host: uriSegments[0],
        deviceId: uriSegments[uriSegments.length - 1],
        hubName: uriSegments[0].split('.')[0],
        sharedAccessSignature: sharedAccessSignature
    };

  /*Codes_SRS_NODE_DEVICE_CLIENT_16_030: [The fromSharedAccessSignature method shall return a new instance of the Client object] */
  return new Client(new Transport(config));
};
```

**Comment by pierreca** [comment]
Hi @wmmihaa, thanks for reporting the issue. it's a known problem that has already been fixed in the `develop` branch and will make it to the next release.
FYI: https://github.com/Azure/azure-iot-sdks/pull/319

**Comment by wmmihaa** [comment]
Thanks @pierreca, any idea when that will be?

**Comment by pierreca** [comment]
within the next 2 weeks if all goes according to plan.

**Comment by wmmihaa** [comment]
@pierreca I pulled the develop branch, and it's not entirely fixed. You've fixed the split part but  not the encoding:

**Master branch:**
```
Client.fromSharedAccessSignature = function (sharedAccessSignature, Transport) {
  /*Codes_SRS_NODE_DEVICE_CLIENT_16_029: [The fromSharedAccessSignature method shall throw a ReferenceError if the sharedAccessSignature argument is falsy.] */
  if (!sharedAccessSignature) throw new ReferenceError('sharedAccessSignature is \'' + sharedAccessSignature + '\'');

  var sas = SharedAccessSignature.parse(sharedAccessSignature);
  var uriSegments = sas.sr.split('/')[0];
  var config = {
    host: uriSegments[0],
    deviceId: uriSegments[uriSegments.length - 1],
    hubName: uriSegments[0].split('.')[0],
    sharedAccessSignature: sharedAccessSignature
  };

  /*Codes_SRS_NODE_DEVICE_CLIENT_16_030: [The fromSharedAccessSignature method shall return a new instance of the Client object] */
  return new Client(new Transport(config));
};
```

**Develop branch:**
```
Client.fromSharedAccessSignature = function (sharedAccessSignature, Transport) {
  /*Codes_SRS_NODE_DEVICE_CLIENT_16_029: [The fromSharedAccessSignature method shall throw a ReferenceError if the sharedAccessSignature argument is falsy.] */
  if (!sharedAccessSignature) throw new ReferenceError('sharedAccessSignature is \'' + sharedAccessSignature + '\'');

  var sas = SharedAccessSignature.parse(sharedAccessSignature);
  var uriSegments = sas.sr.split('/');
  var config = {
    host: uriSegments[0],
    deviceId: uriSegments[uriSegments.length - 1],
    hubName: uriSegments[0].split('.')[0],
    sharedAccessSignature: sharedAccessSignature
  };

  /*Codes_SRS_NODE_DEVICE_CLIENT_16_030: [The fromSharedAccessSignature method shall return a new instance of the Client object] */
  return new Client(new Transport(config));
};
```
**Please consider:**
```
Client.fromSharedAccessSignature = function (sharedAccessSignature, Transport) {
    /*Codes_SRS_NODE_DEVICE_CLIENT_16_029: [The fromSharedAccessSignature method shall throw a ReferenceError if the sharedAccessSignature argument is falsy.] */
    if (!sharedAccessSignature) throw new ReferenceError('sharedAccessSignature is \'' + sharedAccessSignature + '\'');
    
    var sas = SharedAccessSignature.parse(sharedAccessSignature);
    var uri = decodeURIComponent(sas.sr);
    var uriSegments = uri.split('/');
    
    var config = {
        host: uriSegments[0],
        deviceId: uriSegments[uriSegments.length - 1],
        hubName: uriSegments[0].split('.')[0],
        sharedAccessSignature: sharedAccessSignature
    };
    
    /*Codes_SRS_NODE_DEVICE_CLIENT_16_030: [The fromSharedAccessSignature method shall return a new instance of the Client object] */
    return new Client(new Transport(config));
};
```

**Comment by wmmihaa** [comment]
BTW... you have the same issue on azure_iot_device client.js fromSharedAccessSignature (line 141):

Proposal:
```
Client.fromSharedAccessSignature = function (sharedAccessSignature, Transport) {
    /*Codes_SRS_NODE_DEVICE_CLIENT_16_029: [The fromSharedAccessSignature method shall throw a ReferenceError if the sharedAccessSignature argument is falsy.] */
    if (!sharedAccessSignature) throw new ReferenceError('sharedAccessSignature is \'' + sharedAccessSignature + '\'');
    
    var sas = SharedAccessSignature.parse(sharedAccessSignature);
    var uri = decodeURIComponent(sas.sr);
    var uriSegments = uri.split('/');
    
    var config = {
        host: uriSegments[0],
        deviceId: uriSegments[uriSegments.length - 1],
        hubName: uriSegments[0].split('.')[0],
        sharedAccessSignature: sharedAccessSignature
    };
    
    /*Codes_SRS_NODE_DEVICE_CLIENT_16_030: [The fromSharedAccessSignature method shall return a new instance of the Client object] */
    return new Client(new Transport(config));
};
```

**Comment by pierreca** [comment]
@wmmihaa You're absolutely right, sorry I missed that. Thanks for offering a solution. Working on the fix, will update the issue when it's in develop.

**Comment by pierreca** [comment]
Fixed with https://github.com/Azure/azure-iot-sdks/commit/5ad785cc65569ac67a24bcae2744cd8f95e4c7f0

It will make it to the next packaged release which should be end of this week.
